[project]
name = "numba-tsp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Addison Hanrattie", email = "40609224+supersimple33@users.noreply.github.com" }
]
requires-python = ">=3.15"
dependencies = [
    "numba>=0.68.0",
    "numpy>=2.5.3",
    "scipy>=1.18.1",
]

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.4.0",
]
